### ISSUE TITLE
use https method to access external ressources

### ISSUE THREAD

**Issue by TilmannBach** [stura-hftl/wordpress-theme#53]
Die stura seite sieht seit tagen kaputt aus:
jemand hat die Website auf HTTPS umgestellt, nicht aber die externen Quelle (Google font api)

So blockieren einige Browser die externen 'unsicheren' Ressourcen!

Ich habe dazu einen pull-request gemerged. aber da der Server das Repo seit neustem nicht mehr selbstständig pull'ed muss das jemand manuell machen.

see #52 

![unbenannt](https://cloud.githubusercontent.com/assets/2125941/7877371/a9b724e0-05da-11e5-83fa-d76745231a57.PNG)

**Comment by fmalcher** [comment]
Bei mir sind die Font-Ressourcen über HTTPS eingebunden. Wurde das inzwischen gefixt oder gibts noch eine andere Stelle?

![bildschirmfoto 2015-06-02 um 11 36 30](https://cloud.githubusercontent.com/assets/1683147/7932894/b50538ac-091b-11e5-8e22-1bff7160987a.png)

**Comment by TilmannBach** [comment]
ja okay, die Schriftart funktioniert jetzt, aber es gibt gleich eine ganze Reihe weiterer HTTP-Quellen xD

**Comment by Doerki** [comment]
Ja, der Stura ist wohl dabei das fixen bzw. hat das schon teilweise gefixt.

**Comment by TilmannBach** [comment]
ich hab jetzt nix mehr gefunden
